extends: 
  - airbnb-base
  - plugin:@typescript-eslint/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  project: ./tsconfig.json
plugins: 
  - "@typescript-eslint"
rules: 
  "@typescript-eslint/indent":
    - error
    - 2
  "@typescript-eslint/no-explicit-any":
    - off
  "@typescript-eslint/no-unused-vars":
    - error
    - varsIgnorePattern: "[iI]gnored"
