# - cluster:
#     name: nirvana
#     gcp:
#       machineType: g1-small
#     externalDns: true
#     certManager: true
#     prometheus: false
#     nginxIngress: true

- identity:
    gcp:
      project: nirvana-232117
      serviceAccount: true
