version: 2.1
orbs:
  pulumi: pulumi/pulumi@1.0.0
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    environment:
      GOOGLE_CREDENTIALS: gcp.json
    steps:
      - checkout
      - pulumi/login
      - run: yarn
      - run: echo $GCP_JSON > gcp.json
      - run:
          name: Install helm
          command: |
            wget https://storage.googleapis.com/kubernetes-helm/helm-v2.13.0-linux-amd64.tar.gz
            tar -xf helm-v2.13.0-linux-amd64.tar.gz
            sudo cp linux-amd64/helm /usr/bin/helm
            helm init --client-only
      - pulumi/update:
          stack: dev
