version: 2.1
orbs:
  pulumi: pulumi/pulumi@1.0.0
jobs:
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/repo
    environment:
      GOOGLE_CREDENTIALS: gcp.json
    steps:
      - checkout
      - pulumi/login
      - run: yarn
      - run: echo $GCP_JSON > gcp.json
      - run:
          name: Install helm
          command: |
            wget https://storage.googleapis.com/kubernetes-helm/helm-v2.13.0-linux-amd64.tar.gz
            tar -xf helm-v2.13.0-linux-amd64.tar.gz
            sudo cp linux-amd64/helm /usr/bin/helm
            helm init --client-only
      - run:
          name: Install gcloud
          command: |
            wget https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-236.0.0-linux-x86_64.tar.gz
            tar -xf google-cloud-sdk-236.0.0-linux-x86_64.tar.gz
            ./google-cloud-sdk/install.sh --usage-reporting false --override-components core --quiet
      - run: 
          name: Pulumi update
          command: |
            source ./google-cloud-sdk/path.bash.inc
            pulumi update --stack dev --cwd . 
