apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kube-ops-view
  annotations:
    external-dns.alpha.kubernetes.io/ttl: "10"
spec:
  rules:
  - host: "opsview.tmye.me"
    http:
      paths:
      - backend:
          serviceName: kube-ops-view
          servicePort: 80
